// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToInstances = new Map<string, string>();
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f_bsc", // Instance-bnb-0.1
  "bnb-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3_bsc", // Instance-bnb-1
  "bnb-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a_bsc", // Instance-bnb-10
  "bnb-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd_bsc", // Instance-bnb-100
  "bnb-100"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd_xdai", // Instance-xdai-100
  "xdai-100"
);
contractsToInstances.set("0xdf231d99ff8b6c6cbf4e9b9a945cbacef9339178_xdai", // Instance-xdai-1000
  "xdai-1000"
);
contractsToInstances.set("0xaf4c0b70b2ea9fb7487c7cbb37ada259579fe040_xdai", // Instance-xdai-10000
  "xdai-10000"
);
contractsToInstances.set("0xa5c2254e4253490c54cef0a4347fddb8f75a4998_xdai", // Instance-xdai-100000
  "xdai-100000"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd_matic", // Instance-matic-100
  "matic-100"
);
contractsToInstances.set("0xdf231d99ff8b6c6cbf4e9b9a945cbacef9339178_matic", // Instance-matic-1000
  "matic-1000"
);
contractsToInstances.set("0xaf4c0b70b2ea9fb7487c7cbb37ada259579fe040_matic", // Instance-matic-10000
  "matic-10000"
);
contractsToInstances.set("0xa5c2254e4253490c54cef0a4347fddb8f75a4998_matic", // Instance-matic-100000
  "matic-100000"
);
contractsToInstances.set("0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc_mainnet", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0x47ce0c6ed5b0ce3d3a51fdb1c52dc66a7c3c2936_mainnet", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x910cbd523d972eb0a6f4cae4618ad62622b39dbf_mainnet", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0xa160cdab225685da1d56aa342ad8841c3b53f291_mainnet", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0x76d85b4c0fc497eecc38902397ac608000a06607_goerli", // Instance-dai-100
  "dai-100"
);
contractsToInstances.set("0xd4b88df4d29f5cedd6857912842cff3b20c8cfa3_mainnet", // Instance-dai-100
  "dai-100"
);
contractsToInstances.set("0xfd8610d20aa15b7b2e3be39b396a1bc3516c7144_mainnet", // Instance-dai-1000
  "dai-1000"
);
contractsToInstances.set("0x07687e702b410fa43f4cb4af7fa097918ffd2730_mainnet", // Instance-dai-10000
  "dai-10000"
);
contractsToInstances.set("0x23773e65ed146a459791799d01336db287f25334_mainnet", // Instance-dai-100000
  "dai-100000"
);
contractsToInstances.set("0x22aaa7720ddd5388a3c0a3333430953c68f1849b_mainnet", // Instance-cdai-5000
  "cdai-5000"
);
contractsToInstances.set("0x03893a7c7463ae47d46bc7f091665f1893656003_mainnet", // Instance-cdai-50000
  "cdai-50000"
);
contractsToInstances.set("0x2717c5e28cf931547b621a5dddb772ab6a35b701_mainnet", // Instance-cdai-500000
  "cdai-500000"
);
contractsToInstances.set("0xd21be7248e0197ee08e0c20d4a96debdac3d20af_mainnet", // Instance-cdai-5000000
  "cdai-5000000"
);
contractsToInstances.set("0xd96f2b1c14db8458374d9aca76e26c3d18364307_mainnet", // Instance-usdc-100
  "usdc-100"
);
contractsToInstances.set("0x4736dcf1b7a3d580672cce6e7c65cd5cc9cfba9d_mainnet", // Instance-usdc-1000
  "usdc-1000"
);
contractsToInstances.set("0x169ad27a470d064dede56a2d3ff727986b15d52b_mainnet", // Instance-usdt-100
  "usdt-100"
);
contractsToInstances.set("0x0836222f2b2b24a3f36f98668ed8f0b38d1a872f_mainnet", // Instance-usdt-1000
  "usdt-1000"
);
contractsToInstances.set("0x178169b423a011fff22b9e3f3abea13414ddd0f1_mainnet", // Instance-wbtc-0.1
  "wbtc-0.1"
);
contractsToInstances.set("0x610b717796ad172b316836ac95a2ffad065ceab4_mainnet", // Instance-wbtc-1
  "wbtc-1"
);
contractsToInstances.set("0xbb93e510bbcd0b7beb5a853875f9ec60275cf498_mainnet", // Instance-wbtc-10
  "wbtc-10"
);
contractsToInstances.set("0xcc84179ffd19a1627e79f8648d09e095252bc418_goerli", // Instance-dai-1000
  "dai-1000"
);
contractsToInstances.set("0xd5d6f8d9e784d0e26222ad3834500801a68d027d_goerli", // Instance-dai-10000
  "dai-10000"
);
contractsToInstances.set("0x407cceeaa7c95d2fe2250bf9f2c105aa7aafb512_goerli", // Instance-dai-100000
  "dai-100000"
);
contractsToInstances.set("0x833481186f16cece3f1eeea1a694c42034c3a0db_goerli", // Instance-cdai-5000
  "cdai-5000"
);
contractsToInstances.set("0xd8d7de3349ccaa0fde6298fe6d7b7d0d34586193_goerli", // Instance-cdai-50000
  "cdai-50000"
);
contractsToInstances.set("0x8281aa6795ade17c8973e1aedca380258bc124f9_goerli", // Instance-cdai-500000
  "cdai-500000"
);
contractsToInstances.set("0x57b2b8c82f065de8ef5573f9730fc1449b403c9f_goerli", // Instance-cdai-5000000
  "cdai-5000000"
);
contractsToInstances.set("0x05e0b5b40b7b66098c2161a5ee11c5740a3a7c45_goerli", // Instance-usdc-100
  "usdc-100"
);
contractsToInstances.set("0x23173fe8b96a4ad8d2e17fb83ea5dcccdca1ae52_goerli", // Instance-usdc-1000
  "usdc-1000"
);
contractsToInstances.set("0x538ab61e8a9fc1b2f93b3dd9011d662d89be6fe6_goerli", // Instance-usdt-100
  "usdt-100"
);
contractsToInstances.set("0x94be88213a387e992dd87de56950a9aef34b9448_goerli", // Instance-usdt-1000
  "usdt-1000"
);
contractsToInstances.set("0x242654336ca2205714071898f67e254eb49acdce_goerli", // Instance-wbtc-0.1
  "wbtc-0.1"
);
contractsToInstances.set("0x776198ccf446dfa168347089d7338879273172cf_goerli", // Instance-wbtc-1
  "wbtc-1"
);
contractsToInstances.set("0xedc5d01286f99a066559f60a585406f3878a033e_goerli", // Instance-wbtc-10
  "wbtc-10"
);
contractsToInstances.set("0x6bf694a291df3fec1f7e69701e3ab6c592435ae7_goerli", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0x3aac1cc67c2ec5db4ea850957b967ba153ad6279_goerli", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x723b78e67497e85279cb204544566f4dc5d2aca0_goerli", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x0e3a09dda6b20afbb34ac7cd4a6881493f3e7bf7_goerli", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a_avalanche", // Instance-avax-10
  "avax-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd_avalanche", // Instance-avax-100
  "avax-100"
);
contractsToInstances.set("0xaf8d1839c3c67cf571aa74b5c12398d4901147b3_avalanche", // Instance-avax-500
  "avax-500"
);
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f_arbitrum-one", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3_arbitrum-one", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a_arbitrum-one", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd_arbitrum-one", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f_optimism", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3_optimism", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a_optimism", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd_optimism", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0x44dde10deeacd8b91799ff02e4493749ddd320d8_sepolia", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0x2365a6bffbab6f18efb9228f394a6aaeef3f24bc_sepolia", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x3a28921a352d4d8e5a500ed4a3eecfd6e641c783_sepolia", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x38305ee06d4d89adb911c603d0df34de4ae2bfa7_sepolia", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0x6b9a18d1c227a4972bb6512fb8587d12a1356027_sepolia", // Instance-dai-100
  "dai-100"
);
contractsToInstances.set("0x68dad9c7bffe61b44446d894a352e10416c47afa_sepolia", // Instance-dai-1000
  "dai-1000"
);
contractsToInstances.set("0xb62f3d4ade05ab395abbccaa8f45a2a386c67396_sepolia", // Instance-dai-10000
  "dai-10000"
);
contractsToInstances.set("0xedfe671616d42f98e78afabb6907b9e37d1ed900_sepolia", // Instance-dai-100000
  "dai-100000"
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.